version: '3.8'

services:

  redis:
    image: redis:latest
    
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django
    volumes:
      - .:/app
      - ./applications:/app/applications
    ports:
      - "8000:8000"
    env_file:
      - ./env_file.env
    depends_on:
      - db
      - redis
    command: >
        sh -c "until python3 manage.py migrate --noinput; do sleep 1; done &&
        python3 manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:14.10
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yamil_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - db
  
  celery:
    container_name: celery_test
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    command: celery -A celerytask worker --loglevel=INFO 
    volumes:
      - ./celeryworker:/app/
      - ./applications:/app/applications
    env_file:
      - ./celeryworker/env_file.env
    depends_on:
      - redis
      - web
  

